config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
    resources :comments
  end

  resources :farmers do
    resources :messages
  end

  resources :carts, only: [:create, :index, :destroy]
  get "/users_table", to: "users#index", as:"users_table"
  delete "/users_table/:id", to: "users#destroy"
 
  

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  get "/dashboards", to: "dashboards#index", as: 'dashboard'
  get "/dashboards/:id", to: "dashboards#show" 
  
  
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get "/search", to: "products#search", as: "search"
  get "/seasons", to: "seasons#index", as: "season"


  get '/farm_locations', to: 'farm_locations#index'
  get 'farm_locations/:id', to: 'farm_locations#show'
  get '/farm_locations/map/:search', to: "farm_locations#search"

  root to: 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all
    can :search, :all
    can :create,  Comment
    can :read, Comment
    can :manage, Comment, user_id: user.id

    can :create,  Message
    can :read, Message
    can :manage, Message, user_id: user.id
    
    

    if user.farmer?
      can :create, Product
      can :manage, Product, farmer_id: user.farmer.id
      can :manage, Farmer, id: user.farmer.id

      can :destroy, Message, farmer_id: user.farmer.id

      can :destroy, Comment do |comment|
        comment.product.farmer.id == user.farmer.id
      end
    end

    if user.admin?
      can :manage, :all

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products, dependent: :delete_all
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  has_one :user
end

app/models/farm_location.rb
class FarmLocation < ApplicationRecord
  belongs_to :farmer
  geocoded_by :address
  after_validation :geocode
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :farm_locations, dependent: :destroy

  belongs_to :user
  has_one_attached :picture

  validates :name, presence: true, length: { in: 1...20 }
  validates :fruit_types, presence: true, length: { in: 5...50 }
  validates :introduction, presence: true, length: { in: 10...100 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :farmer
  has_one :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :farmer
  has_one_attached :picture
  has_many :cart_products, dependent: :delete_all
  has_many  :carts, through: :cart_products
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { in: 1...50 }
  validates :rank, presence: true, length: { in: 1..2 }
  validates :description, presence: true, length: { in: 1...200 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than: 10 }
  validates :farmer_id, presence: true

  def display_currency
    '$' + sprintf('%.2f', (self.price).to_s)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :farmer, dependent: :destroy
  has_one :cart, dependent: :destroy
  enum user_type: { normal: 0, farmer: 1 }

  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :username, presence: true, length: { in: 3..15 }

  accepts_nested_attributes_for :farmer

  def with_farmer
    build_farmer if farmer.nil?
    self
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET/ this action presents all the products that have been added to the current user's cart in the html view. If there are no products in the cart, it will be redirected to the products page.
  def index
    if user_signed_in? && current_user.cart
      @cart = current_user.cart
    else
      redirect_to products_path
    end
  end

  # POST/ If current user does not have a cart, the cart can be created and the complete status is set to false. When current user click on add product to his/her cart the product will be added to the cart and redirect to the cart page.
  def create
    if !current_user.cart
      cart = Cart.create(completed: false, user_id: current_user.id)
    else
      cart = current_user.cart
    end

    product = Product.find(params[:product_id])
    cart.products << product
    redirect_to carts_path
  end

  # DELETE/ the action can delete products in the current user's cart and keep the newest record.

  def destroy
    cart = current_user.cart
    cart.cart_products.delete(params[:id])
    cart.save

    redirect_to carts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET/ provide the route for presenting home index view.
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET/ provide the route for presenting the users' index view and show all the users in the record followed by its id order.
  def index
    @users = User.all.sort_by { |i| i.id }
  end

  # DELETE/ the user is found by its id and this action deletes the product from the record. After the action, it will redirect to users table page.
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_table_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
  def farmer_pic(farmer)
    if farmer.picture.present?
      farmer.picture
    else
      'farmer_default.jpg'
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def picture_for(product)
    if product.picture.present?
      product.picture
    else
      'fruit_default.jpg'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Local Fruit Market </h1>
<div class="container d-flex flex-column justify-content-center align-items-center mt-4">

  <div class="row">
    <div class="col mb-2">
      <%=image_tag image_path("home/peach-farm.jpg"), alt: "home", size: "370x230" %>
  
      <%=image_tag image_path("home/b-berry-farm.jpg"), alt: "home", size: "280x230" %>
      
      <%=image_tag image_path("home/mango-farm-1.jpg"), alt: "home", size: "300x230" %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%=image_tag image_path("home/strawberry-farm-1.jpg"), alt: "home", size: "300x230" %>
    
      <%=image_tag image_path("home/pear-farm.jpg"), alt: "home", size: "310x230" %>
    
      <%=image_tag image_path("home/dragon-farm.jpg"), alt: "home", size: "340x230" %>
    </div>
  </div>


  <div class="row season-intro d-flex flex-column justify-content-center mt-5 text-aligh-center" style="width:90%">
    <h3>Australian Local Fruits</h3>
    <p>Australia is a country that produces a wide variety of fruits. The land and the climate are diverse, allowing nummerious types of fruits to grow and ripen in all seasons. In winter time, the most abundant selections are lemons, mandarins, and oranges. </p>

    <span id="note">Check our seasonal fruits page to discover more guides >> </span>
    
  </div>

  <div class="row links d-flex justify-content-end mt-3" style="width:90%;" id="link-button">

    <%= link_to "seasonal fruits ", season_path, class: "btn btn-info mt-2 mr-2 mb-2" %>
    <%= link_to "see our products", products_path, class: "btn btn-info mt-2 mr-2 mb-2"%> 
      
   
  </div>
  
  <div class="row col-12 d-flex justify-content-start mt-3" style="width:90%;">
    <a id="contact-us" href="#contact-us"><h3>Contact Us</h3></a>
  </div>

    <div class="row mt-1" style="width:90%;">

      <div class="col-3 d-flex flex-column" id="contact-us-pic">
        <%=image_tag image_path("home/farmer-contact.jpg"), alt: "Us", size: "150x150" %>

        <button class="btn btn-success mb-5" style="width:150px; " type="submit">Submit</button>    
      </div>

    

      <div class="col-9 mb-5 mt-2">  

        <form action="https://formspree.io/mjvozkeg" method="POST">
      
          <div class="form-group">
            <input type="name" name="name" id="name" placeholder="Enter your name" class="form-control">
          </div>

        
          <div class="form-group">
            <input type="email" name="email" id="email" placeholder="Enter your email"  class="form-control">
          </div>
        

          <div class="form-group">
            <textarea class="form-control" name="comment" id="comment" placeholder="Enter your message" ></textarea>
          </div>
            
        </form>
      </div>  
      
  </div>
</div>
  