config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
    resources :comments
  end

  resources :farmers do
    resources :messages
  end

  resources :carts, only: [:create, :index, :destroy]
  get "/users_table", to: "users#index", as:"users_table"
  delete "/users_table/:id", to: "users#destroy"
 
  

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  get "/dashboards", to: "dashboards#index", as: 'dashboard'
  get "/dashboards/:id", to: "dashboards#show" 
  
  
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get "/search", to: "products#search", as: "search"
  get "/seasons", to: "seasons#index", as: "season"


  get '/farm_locations', to: 'farm_locations#index'
  get 'farm_locations/:id', to: 'farm_locations#show'
  get '/farm_locations/map/:search', to: "farm_locations#search"

  root to: 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :farmer
  has_one_attached :picture
  has_many :cart_products, dependent: :delete_all
  has_many  :carts, through: :cart_products
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { in: 1...50 }
  validates :rank, presence: true, length: { in: 1..2 }
  validates :description, presence: true, length: { in: 1...200 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than: 10 }
  validates :farmer_id, presence: true

  def display_currency
    '$' + sprintf('%.2f', (self.price).to_s)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  load_and_authorize_resource

  # searching algorithm will return the records in database which match to the search key words.
  # Also provides some additionally functionality around price searching if the user entered a number only.
  def search
    if params[:search].blank?
      flash[:alert] = "Empty field"
      redirect_to(root_path)
    else

      @parameter = params[:search].downcase

      is_number = @parameter.match(/^[0-9]+$/)
      if (is_number)
        price_target = @parameter.to_i
        @results_product = Product.all.where("price <= :price_target", price_target: price_target)
      else
        @results_product = Product.all.where("lower(title) LIKE :search", search: "%#{@parameter}%")
        @results_product = Product.all.where("lower(description) LIKE :search", search: "%#{@parameter}%")
      end

      @results_farmer = Farmer.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end

  # GET/ this acion returns all the products in the products table and sends data to the index view
  # eager loading is added here to minimize database calls.
  def index
    @products = Product.with_attached_picture.all
  end

  # GET/ Firstly, using set_product method to find the product. It provides the route for rendering show page
  def show
  end

  # POST/ render the form for the creation of a new product
  def new
    @product = Product.new
  end

  # POST/ this action creates a new product with the filled in html form, because the farmer id is assigned directedly from the current farmer id, the merge method is added.
  def create
    @product = Product.create(product_params.merge({ farmer_id: current_user.farmer.id }))

    # If the filled in has any validation errors, the new form will be rendered and if the product is added successfully, it will redirected to the product show page.
    if @product.errors.any?
      render :new
    else
      flash[:success] = "Your product is added to the product page"
      redirect_to @product
    end
  end

  # GET/  Before render the edit html in view, using set_product method to find the product
  def edit
  end

  # PUT/ Updates the existing product with new filled in params form from edit html , uses set_product method to find the product. After the action, it will redirect to product show page.
  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  # DELETE/ Before using this action to delete the product from the record, the set_product method is used to find the product. After the action, it will redirect to products page.
  def destroy
    @product.destroy
    redirect_to dashboard_path
  end

  private

  # Use query string parameter to find product's id
  def set_product
    @product = Product.find(params[:id])
  end

  # allows product's attributes to be update and created.
  def product_params
    params.require(:product).permit(:title, :rank, :quantity, :description, :price, :picture)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def picture_for(product)
    if product.picture.present?
      product.picture
    else
      'fruit_default.jpg'
    end
  end
end

app/views/products/_card.html.erb
  <div class="card my-3 col-md-4 col-xs-12" style="max-width:18%; min-width:18rem;">
    <%= image_tag picture_for(product) , alt: "#{product.title} image", class: 'card-img-top img_fluid mt-3' %>

    <div class="card-body">
      <h6 class="card-title"><%= product.title %></h6>
      <h6 class="card-text mb-2 text-muted">Quantity: <%= product.quantity %></h6>

      <h6 class="card-subtitle mb-2 text-muted">Price: <%= number_to_currency(product.price) %> aud</h6>
    

      <%= link_to product_path(product) do %>
        <%= image_tag 'view.png', size: '40x40' %>
      <% end %>
    
      <% if user_signed_in? %>
        <%= link_to carts_path(product_id: product.id), method: :post do %> 
          <%= image_tag 'add-to.png', size: '35x35' %>
        <% end %>

      
        <% if current_user.user_type == "farmer" && current_user.farmer == product.farmer || current_user.admin? %>
        
          <%= link_to edit_product_path(product.id) do %>
            <%= image_tag 'edit.png', size: '30x30' %>
          <% end %>

          <%= link_to product_path(product.id), method: :delete, data: {
            confirm: "Delete #{product.title} confrimed?"
          } do %> 
            <%= image_tag 'delete.png', size: '30x30' %>
          <% end %> 
        <% end %>

      <% else %>
        <%= link_to user_session_path do %> 
          <%= image_tag 'add-to.png', size: '35x35' %>
        <% end %>

      

      <% end %>


     
 
      
        
    </div>

  </div>

app/views/products/_form.html.erb
<%= form_with model: @product, url: products_path+ "/#{@product.id}",  local: true do |form| %>



  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= form.label :rank %>
    <%= form.text_field :rank, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>
  
  
  <div class="custom-file">
    <%= form.label :picture, class: 'custom-file-label' %>
    <%= form.file_field :picture, class: 'custom-file-input', id: 'customFile' %>
  </div>

  

  <div class="d-flex justify-content-between" id="new-product-links">
    <%= form.submit class: 'btn btn-success my-2' %>
    <%= link_to 'Back', products_path, class: 'btn btn-outline-success my-2' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h3 class="mt-5 mb-5">Edit <%= @product.title %></h3>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Featured Products</h1>
<div class="row justify-content-around">
  <% @products.each do |product| %>
    <%= render 'card', product: product %>
  <% end %>
  
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

  <div class="d-flex justify-content-center">
    <%= render 'form' %>
  </div>

  

app/views/products/search.html.erb
<h4 class="mt-3 mb-4">Search Result</h4>
<ol>
  <% @results_product.each do |result| %>
    <li class=" mb-3"><%= link_to "#{result.title} ($#{result.price}) ", product_path(result) %><br>
      <%= "#{result.description}"  %>
    </li>
  <% end %>

  <% @results_farmer.each do |result| %>
    <li><%= link_to "#{result.name}", farmer_path(result)%></li>
  <% end %>


</ol>

app/views/products/show.html.erb
<% if flash[:success] %>
  <p><%= flash[:success] %></p>
<% end %>


<div class="row">
  <div class="col-5 md-5 mt-5  ">
    <%= image_tag picture_for(@product) , alt: "#{@product.title} image", class: 'mt-2', style: 'width:80%;' %>
  </div>

  <div class="col-7 md-5  mt-5 d-flex flex-column justify-content-center" id="product-show">
    <h4><%= @product.title %></h4>
    <div>
      <strong>Farmer:  </strong>
      <span><%= @product.farmer.name %></span>
    </div>

    <div>
      <strong>Rank:  </strong>
      <span><%= @product.rank %></span>
    </div>

    <div>
      <strong>Quantity:  </strong>
      <span><%= @product.quantity %></span>
    </div>

    <div>
      <strong>Description:  </strong>
      <span><%= @product.description %></span>
    </div>

    <div>
      <strong>Price: </strong>
      <span><%= number_to_currency(@product.price) %> aud</span>
    </div>
    
  </div>
  
</div>


<div class=" row col-12 show-edit-delete d-flex justify-content-end mt-3" >
    
    <% if user_signed_in? %>
       <%= link_to carts_path(product_id: @product.id), method: :post do %> 
          <%= image_tag 'add-to.png', size: '35x35' %>
        <% end %> 
      

      <% if user_signed_in? && (current_user.farmer == @product.farmer|| current_user.admin?) %>
          <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-info sm ml-2 mr-2'%>
          <%= link_to 'Delete', product_path(@product), method: :delete, class: 'btn btn-danger sm mr-2', data: { confirm: "Really delete #{@product.title}?"} %>
      <% end %>
    <% end %>

    <%= link_to 'javascript:history.go(-1);' do %>
      <%= image_tag 'back.png', size: '30x30' %>
    <% end %> 
              
</div>

<div class=" row mt-5 ">
  <div class="col-6 mt-4">
    <%= render @product.comments %>
  </div>

  <div class="col-6">
    <h3>Add a comment: </h3>
    <%= render 'comments/form' %>
  </div> 
  
</div>