config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
    resources :comments
  end

  resources :farmers do
    resources :messages
  end

  resources :carts, only: [:create, :index, :destroy]
  get "/users_table", to: "users#index", as:"users_table"
  delete "/users_table/:id", to: "users#destroy"
 
  

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  get "/dashboards", to: "dashboards#index", as: 'dashboard'
  get "/dashboards/:id", to: "dashboards#show" 
  
  
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get "/search", to: "products#search", as: "search"
  get "/seasons", to: "seasons#index", as: "season"


  get '/farm_locations', to: 'farm_locations#index'
  get 'farm_locations/:id', to: 'farm_locations#show'
  get '/farm_locations/map/:search', to: "farm_locations#search"

  root to: 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all
    can :search, :all
    can :create,  Comment
    can :read, Comment
    can :manage, Comment, user_id: user.id

    can :create,  Message
    can :read, Message
    can :manage, Message, user_id: user.id
    
    

    if user.farmer?
      can :create, Product
      can :manage, Product, farmer_id: user.farmer.id
      can :manage, Farmer, id: user.farmer.id

      can :destroy, Message, farmer_id: user.farmer.id

      can :destroy, Comment do |comment|
        comment.product.farmer.id == user.farmer.id
      end
    end

    if user.admin?
      can :manage, :all

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products, dependent: :delete_all
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  has_one :user
end

app/models/farm_location.rb
class FarmLocation < ApplicationRecord
  belongs_to :farmer
  geocoded_by :address
  after_validation :geocode
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :farm_locations, dependent: :destroy

  belongs_to :user
  has_one_attached :picture

  validates :name, presence: true, length: { in: 1...20 }
  validates :fruit_types, presence: true, length: { in: 5...50 }
  validates :introduction, presence: true, length: { in: 10...100 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :farmer
  has_one :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :farmer
  has_one_attached :picture
  has_many :cart_products, dependent: :delete_all
  has_many  :carts, through: :cart_products
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { in: 1...50 }
  validates :rank, presence: true, length: { in: 1..2 }
  validates :description, presence: true, length: { in: 1...200 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than: 10 }
  validates :farmer_id, presence: true

  def display_currency
    '$' + sprintf('%.2f', (self.price).to_s)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :farmer, dependent: :destroy
  has_one :cart, dependent: :destroy
  enum user_type: { normal: 0, farmer: 1 }

  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :username, presence: true, length: { in: 3..15 }

  accepts_nested_attributes_for :farmer

  def with_farmer
    build_farmer if farmer.nil?
    self
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET/ this action presents all the products that have been added to the current user's cart in the html view. If there are no products in the cart, it will be redirected to the products page.
  def index
    if user_signed_in? && current_user.cart
      @cart = current_user.cart
    else
      redirect_to products_path
    end
  end

  # POST/ If current user does not have a cart, the cart can be created and the complete status is set to false. When current user click on add product to his/her cart the product will be added to the cart and redirect to the cart page.
  def create
    if !current_user.cart
      cart = Cart.create(completed: false, user_id: current_user.id)
    else
      cart = current_user.cart
    end

    product = Product.find(params[:product_id])
    cart.products << product
    redirect_to carts_path
  end

  # DELETE/ the action can delete products in the current user's cart and keep the newest record.

  def destroy
    cart = current_user.cart
    cart.cart_products.delete(params[:id])
    cart.save

    redirect_to carts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET/ provide the route for presenting home index view.
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
  def farmer_pic(farmer)
    if farmer.picture.present?
      farmer.picture
    else
      'farmer_default.jpg'
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def picture_for(product)
    if product.picture.present?
      product.picture
    else
      'fruit_default.jpg'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to products_path, class: 'navbar-brand ml-3' do %> 
    <%= image_tag 'dragon-fruit.png', size: '50x50' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to root_path, class: 'btn btn-light ml-1 mb-1' do %>
        <%= image_tag 'home.png', size: '30x30' %>
      <% end %>

      <%= link_to farmers_path, class: 'btn btn-light ml-1 mb-1' do %>
        <%= image_tag 'farmer.png', size: '30x30' %>
      <% end %>

      <%= link_to farm_locations_path, class: 'btn btn-light ml-1 mb-1' do %>
        <%= image_tag 'map.png', size: '30x30' %>
      <% end %>

      <%= link_to products_path, class: 'btn btn-light ml-1 mb-1' do %>
        <%= image_tag 'products.png', size: '30x30' %>
      <% end %>
      
    
      <% if user_signed_in? && current_user.farmer %> 
          <%= link_to new_product_path, class: 'btn btn-light mb-1 ml-1' do %>
            <%= image_tag 'add-product.png', size: '25x25' %>
          <% end %>
          <%= link_to dashboard_path, class: 'btn btn-light mb-1 ml-1' do %> 
            <%= image_tag 'admin.png', size: '30x30' %>
          <% end %>

        <% elsif user_signed_in? && current_user.admin %>
          <%= link_to dashboard_path, class: 'btn btn-light mb-1 ml-1' do %> 
            <%= image_tag 'admin.png', size: '30x30' %>
          <% end %>
          <%= link_to users_table_path, class: 'btn btn-light mb-1 ml-1' do %> 
            <%= image_tag 'users.png', size: '30x30' %>
          <% end %>
      <% end %>

      <% if user_signed_in? %>
        <%= link_to carts_path, class: 'btn btn-light ml-1 mb-1' do %>
          <%= image_tag 'cart.png', size: '30x30' %>
        <% end %>
      <% end %>
    </div>

    <div class="navbar-nav">

      <div class="ml-4 mr-2">  
        <div class="form-inline my-2 my-lg-0 d-flex justify-content-center ml-5">
          <%= form_tag(search_path, :method => "get", class: "form-inline my-2 my-lg-0 d-flex justify-content-center") do %>   
            <%= search_field_tag :search, params[:search], class: "form-control", style: 'width:80%;'%>  
            <button class="btn btn-light my-2 my-sm-0" type="submit"><%= image_tag 'search.png', size: '30x30' %></button> 
          <% end %>
        </div>
      </div>

      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger ml-1 mb-1', id: "logout" %>
      <% else %>
        <%= link_to 'User sign up', new_user_registration_path(user_type: "normal"), class: 'btn btn-outline-success mb-1 ml-1', id: "sign-up" %>
        <%= link_to 'Farmer sign up', new_user_registration_path(user_type: "farmer"), class: 'btn btn-outline-success mb-1 ml-1', id: "sign-up"  %>

        <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-success mb-1 ml-1', id: "login" %>
      <% end %>

      <%= link_to root_path(anchor: "contact-us"), class: 'btn btn-light ml-1 mb-1' do %>
        <%= image_tag 'contact-us.png', size: '25x25' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FruitMarketplaceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= favicon_link_tag asset_path('pear.png') %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag :application %> 
    
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </head>

  <body>

    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>